export const COLOURS ={
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
    darkGreen: '#006A42',
}

export const Items = [
    {
        id:1,
        category:'product',
        productName:'MI Super Bass Bluetooth Wireless Headphones',
        productPrice:1000,
        discription: 'Up to 20 hours life | Super powerful Bass | 40mm dynamic driver | baleyo cha yeakdami naya jasti cha kai ne chinta lenu pardna',
        isOff:true,
        offPercentage:10,
        Brand: 'Vega',
        Graphics: 'Digital',
        SubCategory: 'Full Helmet',
        ProductModel: 'Exo-391',
        Manufacturer: 'Nepal',
        postName: 'Roshan ShowRoom',
        phNumber: '9864260404',
        productImage:require('../database/images/products/hel1.png'),
        isAvailable:true,
        productImageList: [
            require('../database/images/products/hel1.png'),
            require('../database/images/products/Mi2.png'),
            require('../database/images/products/Mi3.png'),
        ]
    },
    {
        id:2,
        category:'product',
        productName:'boat Rockers 450 Bluetooth Wireless Headphones',
        productPrice:1985,
        discription: 'boat Rockerz 450 M is an on-ear wireless headset | Super powerful boat | Fast charging with Lithium Battery | baleyo cha yeakdami naya jasti cha kai ne chinta lenu pardna',
        isOff:true,
        offPercentage:18,
        Brand: 'Yetia',
        Graphics: '',
        SubCategory: 'Full Helmet',
        ProductModel: 'Exo-433',
        Manufacturer: 'Australia',
        postName: 'Romee ShowRoom',
        phNumber: '9849644940',
        productImage:require('../database/images/products/hel2.png'),
        isAvailable:true,
        productImageList: [
            require('../database/images/products/hel2.png'),
            require('../database/images/products/boat2.png'),
            require('../database/images/products/boat3.png'),
        ]
    },
    {
        id:3,
        category:'accessory',
        productName:'boAt Airdrops 441',
        productPrice:1999,
        discription: 'Fly into your workouts with precise tones that inspires and energyze your systems | USB, networking system | Better than any other product with smooth interface',
        isOff:false,
        Brand: 'Scorpio',
        Graphics: 'Analague',
        SubCategory: 'Full Helmet',
        ProductModel: 'Air-731',
        postName: 'Roshan ShowRoom',
        phNumber: '9851009801',
        productImage:require('../database/images/accessories/hel3.png'),
        isAvailable:false,
        productImageList: [
            require('../database/images/accessories/hel3.png'),
            require('../database/images/accessories/boatairpods2.png'),
            require('../database/images/accessories/boatairpods3.png'),
        ]
    },
    {
        id:4,
        category:'accessory',
        productName:'boAt Rockers 255 Pro+',
        productPrice:499,
        discription: 'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatable with any devices | Brand new with sealed pack no worry about anything',
        isOff:true,
        offPercentage:10,
        Brand: 'Apache',
        Graphics: 'Modern',
        SubCategory: 'Half Helmet',
        ProductModel: 'Y8',
        Manufacturer: 'Japan',
        postName: 'Samrachana Nepal',
        phNumber: '9862166088',
        productImage:require('../database/images/accessories/hel4.png'),
        isAvailable:true,
        productImageList: [
            require('../database/images/accessories/hel4.png'),
            require('../database/images/accessories/boatrockerz2.png'),
            require('../database/images/accessories/boatrockerz3.png'),
        ]
    },
    {
        id:5,
        category:'accessory',
        productName:'boAt Bassheads 242',
        productPrice:1499,
        discription: 'The unbeatable boAt signature sound shines through no matter what you play with full echo sound | High quality 450fz Frequency | Brand new with sealed pack no worry about anything',
        isOff:false,
        Brand: 'Vega',
        Graphics: 'Digital',
        SubCategory: 'Full Helmet',
        ProductModel: 'Exo-375',
        Manufacturer: 'Nepal',
        postName: 'Roshan ShowRoom',
        phNumber: '9864260404',
        productImage:require('../database/images/accessories/hel5.png'),
        isAvailable:false,
        productImageList: [
            require('../database/images/accessories/hel5.png'),
            require('../database/images/accessories/boatbassheads2.png'),
            require('../database/images/accessories/boatbassheads3.png'),
        ]
    },
    {
        id:6,
        category:'accessory',
        productName:'Boult Audio AirBass Prepods TWS',
        productPrice:1299,
        discription: 'Touching control and Voice assistant: With one multifunction AirBass and sound is full quality| High quality 450fz Frequency | WaterProof facility| Brand new with sealed pack no worry about anything',
        isOff:false,
        Brand: 'Dott',
        Graphics: 'Simple',
        SubCategory: 'Full Helmet',
        ProductModel: 'DDA-996',
        Manufacturer: 'Germany',
        postName: 'Dott ShowRoom Nepal',
        phNumber: '9818673074',
        productImage:require('../database/images/accessories/hel6.png'),
        isAvailable:true,
        productImageList: [
            require('../database/images/accessories/hel6.png'),
            require('../database/images/accessories/boultairbass2.png'),
            require('../database/images/accessories/boultairbass3.png'),
        ]
    },
    
]